on:
  workflow_run:
    workflows:
      - "CI/CD API"
      - "CI/CD UI"
    types:
      - completed

jobs:
  send-failure-email:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Set up SMTP
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          echo "Failed step: ${{ github.event.workflow_run.conclusion }}" > email-body.txt
          echo "Workflow URL: ${{ github.event.workflow_run.html_url }}" >> email-body.txt
          echo "Repository: ${{ github.repository }}" >> email-body.txt
          echo "Branch: ${{ github.event.workflow_run.head_branch }}" >> email-body.txt
          echo "Commit: ${{ github.event.workflow_run.head_commit.id }}" >> email-body.txt
          echo "Commit Message: ${{ github.event.workflow_run.head_commit.message }}" >> email-body.txt
          echo "Commit URL: ${{ github.event.workflow_run.head_commit.url }}" >> email-body.txt
          echo "Sender: ${{ github.event.workflow_run.sender.login }}" >> email-body.txt
          cat email-body.txt | mail -s "Workflow Failed: ${{ github.event.workflow_run.name }}" "$TO_EMAIL"
