name: email notifications
on:
  workflow_run:
    workflows:
      - "CI/CD API"
      - "CI/CD UI"
    types:
      - completed

jobs:
  send-failure-email:
    runs-on: ubuntu-latest
    if: ${{ always() }}

    steps:
      - name: Set up SMTP
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          echo "Completed step: ${{ github.event.workflow_run.conclusion }}" > email-body.txt
          echo "Workflow URL: ${{ github.event.workflow_run.html_url }}" >> email-body.txt
          echo "Repository: ${{ github.repository }}" >> email-body.txt
          echo "Branch: ${{ github.event.workflow_run.head_branch }}" >> email-body.txt
          echo "Commit: ${{ github.event.workflow_run.head_commit.id }}" >> email-body.txt
          echo "Commit Message: ${{ github.event.workflow_run.head_commit.message }}" >> email-body.txt
          echo "Commit URL: ${{ github.event.workflow_run.head_commit.url }}" >> email-body.txt
          echo "Sender: tresams362@gmail.com" >> email-body.txt
          cat email-body.txt

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: 10.50.129.54
          server_port: 465
          username: "APAdminqa_op"
          password: "3flatGROUNDtown66"
          subject: "Workflow Completed: ${{ github.event.workflow_run.name }}"
          body: $(cat email-body.txt)
          from: APAdminqa_op@sonicwall.com
          to: msebastian@sonicwall.com
          
